#!/usr/bin/env sh
# Check if the "--no-lint" option is provided in the push command
while read local_ref local_sha remote_ref remote_sha; do
  if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
    # A branch is being deleted; no need to lint
    exit 0
  fi
done

# Run ESLint only if the "--no-lint" option is not provided
if [ ["$*" != *"--no-lint"*] ]; then
  # Replace 'npm run lint' with your actual ESLint command
  npm run lint
  eslint_exit_code=$?
  if [ $eslint_exit_code -ne 0 ]; then
    echo "ESLint check failed. Push aborted."
    exit $eslint_exit_code
  fi
fi




. "$(dirname -- "$0")/_/husky.sh"

yarn build
